server:
  contextPath: /web-app
  port: 8887

zuul:
  routes:
    auth:
      path: /auth/**
      url: http://localhost:8889/auth/
      sensitive-headers:
    contact:
      path: /contacts/**
      url: http://localhost:8886/
      sensitive-headers:
    profile:
      path: /profiles/**
      url: http://localhost:8885/
      sensitive-headers:

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8887/web-app/auth/oauth/token
      userAuthorizationUri: http://localhost:8887/web-app/auth/oauth/authorize
      clientId: web-app
      preEstablishedRedirectUri: http://localhost:8887/web-app/login
      registeredRedirectUri: http://localhost:8887/web-app/login
      useCurrentUri: false
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

#security:
#  oauth2:
#    client:
#      accessTokenUri: http://auth-service/auth/oauth/token
#      userAuthorizationUri: http://auth-service/auth/oauth/authorize
#      clientId: myauthserver
#      clientSecret: verysecretpassword
#    resource:
#      userInfoUri: http://auth-service/auth/user
#
## Proxies the calls to http://localhost:8080/api/* to our REST service at http://localhost:8081/*
## and automatically includes our OAuth2 token in the request headers
#zuul:
#  routes:
#    internalApi:
#      path: /api/**
#      url: http://localhost:8081
#    externalApi:
#      path: /external/**
#      url: http://some.external.webservice/
#
## Make sure the OAuth2 token is only relayed when using the internal API,
## do not pass any authentication to the external API
#proxy:
#  auth:
#    routes:
#      internalApi: oauth2
#      externalApi: none