server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Predkel/microservices-configuration

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/